services:
  frontend-fr:
    build:
      context: ../../../frontend
      dockerfile: ../devops/docker/Dockerfile.front
    depends_on:
      - backend-fr
    environment:
      PUBLIC_API_LOCAL_URL: "http://backend-fr:80"
      PUBLIC_API_URL: "${PUBLIC_API_URL:-https://comparia.beta.gouv.fr}"
    ports:
      - "3001:3000"

  backend-fr:
    environment:
      LOGDIR: /data
      DEFAULT_COUNTRY_PORTAL: fr
      COMPARIA_DB_URI: "${COMPARIA_DB_URI_FR:-postgresql://postgres:postgres@postgres-fr:5432/comparia_fr}"
      COMPARIA_REDIS_HOST: redis-fr
      OPENROUTER_API_KEY:
      ALBERT_API_KEY:
      GOOGLE_APPLICATION_CREDENTIALS:
      HF_PUSH_DATASET_KEY:
      AWS_SECRET_ACCESS_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_ENDPOINT_URL:
      AWS_DEFAULT_REGION:
      SENTRY_DSN:
      SENTRY_ENVIRONMENT:
      SENTRY_SAMPLE_RATE:
      LOG_FORMAT:
      ALTCHA_HMAC_KEY:
    build:
      context: ../../..
      dockerfile: devops/docker/Dockerfile
    ports:
      - "8001:80"
