version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/devops/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/devops/instances/redis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/devops/instances/postgres"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/devops/standalone_docker_install"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
