services:
  postgres-simple:
    image: postgres:18
    environment:
      POSTGRES_USER: comparia
      POSTGRES_PASSWORD: comparia
      POSTGRES_DB: comparia
    volumes:
      - db-data:/var/lib/postgresql
      - ./schema.sql:/tmp/schema.sql:ro
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      comparia-net:
        aliases:
          - postgres

volumes:
  db-data:

networks:
  comparia-net:
    external: true
