apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comparia.fullname" . }}-frontend
  labels:
    {{- include "comparia.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      {{- include "comparia.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "comparia.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: {{ include "comparia.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "comparia.frontendImage" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - secretRef:
                name: {{ include "comparia.secretName" . }}
          env:
            - name: PORT
              value: "80"
            - name: PUBLIC_API_URL
              value: {{ .Values.frontend.publicApiUrl | quote }}
            - name: PUBLIC_API_LOCAL_URL
              value: "http://{{ include "comparia.fullname" . }}-backend:{{ .Values.service.backend.port }}"
            - name: PUBLIC_DISABLED_LOCALES
              value: {{ .Values.frontend.disabledLocales | quote }}
            {{- with .Values.frontend.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
