apiVersion: v1
kind: Service
metadata:
  name: {{ include "comparia.fullname" . }}-frontend
  labels:
    {{- include "comparia.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  sessionAffinity: ClientIP
  type: ClusterIP
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "comparia.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
