FROM public.ecr.aws/docker/library/node:24.3

ARG GIT_COMMIT
ENV GIT_COMMIT=$GIT_COMMIT

ENV PUBLIC_API_URL="https://alpha.comparia.beta.gouv.fr/api"

WORKDIR /app
COPY ./package.json /app
RUN yarn install
COPY ./ /app
RUN npm run build
EXPOSE 80
CMD ["node", "build"]
