FROM public.ecr.aws/docker/library/node:24.4
ARG GIT_COMMIT
ENV PUBLIC_GIT_COMMIT=$GIT_COMMIT

ARG PUBLIC_API_URL
ENV PUBLIC_API_URL=$PUBLIC_API_URL



WORKDIR /app
RUN npm install -g vite
COPY ./package.json ./yarn.lock /app
RUN yarn install
COPY ./ /app

RUN vite build

EXPOSE 80
CMD ["node", "build"]
