"""initial_schema

Revision ID: 09abb45aa086
Revises: 
Create Date: 2026-05-18 16:40:47.379046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09abb45aa086'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('session_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visitor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cohorts', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('custom_models_selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_id_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_msg_a_id', sa.Uuid(), nullable=True),
    sa.Column('llm_id_b', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_msg_b_id', sa.Uuid(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_analyzed', sa.Boolean(), nullable=True),
    sa.Column('contains_pii', sa.Boolean(), nullable=True),
    sa.Column('contains_spam', sa.Boolean(), nullable=True),
    sa.Column('short_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_reason', sa.String(), nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['system_msg_a_id'], ['system_message.id'], ),
    sa.ForeignKeyConstraint(['system_msg_b_id'], ['system_message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_msg_a_id'),
    sa.UniqueConstraint('system_msg_b_id')
    )
    op.create_table('turn',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comparison_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('choice', sa.String(), nullable=True),
    sa.Column('llm_msg_a_id', sa.Uuid(), nullable=True),
    sa.Column('keyword_annotations_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_annotation_a', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_msg_b_id', sa.Uuid(), nullable=True),
    sa.Column('keyword_annotations_b', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_annotation_b', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison.id'], ),
    sa.ForeignKeyConstraint(['llm_msg_a_id'], ['llm_message.id'], ),
    sa.ForeignKeyConstraint(['llm_msg_b_id'], ['llm_message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('llm_msg_a_id'),
    sa.UniqueConstraint('llm_msg_b_id')
    )
    op.create_table('user_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_message')
    op.drop_table('turn')
    op.drop_table('comparison')
    op.drop_table('system_message')
    op.drop_table('llm_message')
    # ### end Alembic commands ###
