"""remove_unique_constraint_on_system_msg_ids

Revision ID: 137fbd6418e6
Revises: 09abb45aa086
Create Date: 2026-05-18 18:08:28.136828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '137fbd6418e6'
down_revision: Union[str, Sequence[str], None] = '09abb45aa086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comparison_system_msg_a_id_key'), 'comparison', type_='unique')
    op.drop_constraint(op.f('comparison_system_msg_b_id_key'), 'comparison', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('comparison_system_msg_b_id_key'), 'comparison', ['system_msg_b_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('comparison_system_msg_a_id_key'), 'comparison', ['system_msg_a_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
