"""make LLMLab logo optional

Revision ID: 269a5fc3959c
Revises: d2b7f4a9c6e1
Create Date: 2026-09-09 14:17:04.189582

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "269a5fc3959c"
down_revision: Union[str, Sequence[str], None] = "d2b7f4a9c6e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("llm_lab", "logo", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("llm_lab", "logo", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
