"""add LLMData, LLMEndpoint, LLMLab, LLMLicence

Revision ID: 4e31217520dd
Revises: d9b83b7f2988
Create Date: 2026-06-15 11:00:43.707153

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e31217520dd"
down_revision: Union[str, Sequence[str], None] = "d9b83b7f2988"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_endpoint",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_base", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("api_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_endpoint_name"), "llm_endpoint", ["name"], unique=False
    )
    op.create_table(
        "llm_lab",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("logo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("origin_country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_license",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reuse", sa.Boolean(), nullable=False),
        sa.Column("commercial_use", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_data",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("lab_id", sa.Uuid(), nullable=False),
        sa.Column("license_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=True),
        sa.Column("human_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rate_limited", sa.Boolean(), nullable=False),
        sa.Column("release_date", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("knowledge_cutoff", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("arch", sa.String(), nullable=False),
        sa.Column("params", sa.Float(), nullable=False),
        sa.Column("active_params", sa.Float(), nullable=True),
        sa.Column("context_tokens", sa.Integer(), nullable=True),
        sa.Column("quantization", sa.String(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("public_weights", sa.Boolean(), nullable=False),
        sa.Column("public_training_data", sa.Boolean(), nullable=False),
        sa.Column("public_training_code", sa.Boolean(), nullable=False),
        sa.Column("eu_hostable", sa.Boolean(), nullable=False),
        sa.Column("price_in", sa.Float(), nullable=False),
        sa.Column("price_out", sa.Float(), nullable=False),
        sa.Column("system_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["llm_endpoint.id"]),
        sa.ForeignKeyConstraint(["lab_id"], ["llm_lab.id"]),
        sa.ForeignKeyConstraint(["license_id"], ["llm_license.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_data_human_id"), "llm_data", ["human_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_data_human_id"), table_name="llm_data")
    op.drop_table("llm_data")
    op.drop_table("llm_license")
    op.drop_table("llm_lab")
    op.drop_index(op.f("ix_llm_endpoint_name"), table_name="llm_endpoint")
    op.drop_table("llm_endpoint")
    # ### end Alembic commands ###
