"""simplify system_msg_*

Revision ID: 83c86b798214
Revises: b7c4d1e8f9a2
Create Date: 2026-06-29 16:28:58.607048

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "83c86b798214"
down_revision: Union[str, Sequence[str], None] = "b7c4d1e8f9a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("comparison_system_msg_b_id_fkey"), "comparison", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("comparison_system_msg_a_id_fkey"), "comparison", type_="foreignkey"
    )
    op.drop_column("comparison", "system_msg_a_id")
    op.drop_column("comparison", "system_msg_b_id")
    op.drop_table("system_message")

    op.add_column(
        "comparison",
        sa.Column("system_msg_a", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "comparison",
        sa.Column("system_msg_b", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comparison", "system_msg_b")
    op.drop_column("comparison", "system_msg_a")

    op.create_table(
        "system_message",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("system_message_pkey")),
    )
    op.add_column(
        "comparison",
        sa.Column("system_msg_b_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "comparison",
        sa.Column("system_msg_a_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("comparison_system_msg_a_id_fkey"),
        "comparison",
        "system_message",
        ["system_msg_a_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("comparison_system_msg_b_id_fkey"),
        "comparison",
        "system_message",
        ["system_msg_b_id"],
        ["id"],
    )
    # ### end Alembic commands ###
