"""drop Comparison.session_hash

Revision ID: 88e025e5dbfa
Revises: 09abb45aa086
Create Date: 2026-05-20 11:41:16.076555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88e025e5dbfa'
down_revision: Union[str, Sequence[str], None] = '09abb45aa086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparison', 'session_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('session_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
