"""add PromptCheckResult table

Revision ID: c24f368ecff0
Revises: f1a2b3c4d5e6
Create Date: 2026-08-06 15:47:14.369709

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c24f368ecff0"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_check_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=True),
        sa.Column("decision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("triggered", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_proceeded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["turn_id"], ["turn.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("turn_id"),
    )
    op.drop_index(
        op.f("ix_turn_prompt_check_created_at"),
        table_name="turn",
        postgresql_where="(guardrail ? 'decision'::text)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_turn_prompt_check_created_at"),
        "turn",
        ["created_at"],
        unique=False,
        postgresql_where="(guardrail ? 'decision'::text)",
    )
    op.drop_table("prompt_check_result")
    # ### end Alembic commands ###
