"""add Comparison 'revealed' and 'revealed_at'

Revision ID: c523a8830386
Revises: d1f4a2e7c9b5
Create Date: 2026-07-06 13:45:44.593607

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c523a8830386"
down_revision: Union[str, Sequence[str], None] = "d1f4a2e7c9b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comparison",
        sa.Column("revealed", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "comparison", sa.Column("revealed_at", postgresql.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comparison", "revealed_at")
    op.drop_column("comparison", "revealed")
    # ### end Alembic commands ###
