"""link Comparison.llm_id_a|b to LLMData.id

Revision ID: c6d5610142dc
Revises: 4e31217520dd
Create Date: 2026-06-15 12:41:36.607686

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6d5610142dc"
down_revision: Union[str, Sequence[str], None] = "4e31217520dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# start custom
import json
from pathlib import Path


def update_table_ids(reversed: bool = False):
    EXTRAS_DIR = Path(__file__).parent.parent / "extras"
    RAW_DATA_PATH = EXTRAS_DIR / "models.json"

    raw_orgas = json.loads(RAW_DATA_PATH.read_text())
    llm_ids_map = {}

    for raw_orga in raw_orgas:
        llm_ids_map |= {
            raw_llm["id"]: raw_llm["db_id"] for raw_llm in raw_orga["models"]
        }

    if reversed:
        llm_ids_map = {v: k for k, v in llm_ids_map.items()}
        t = sa.Uuid
    else:
        t = sa.VARCHAR

    table = sa.table(
        "comparison",
        sa.column("llm_id_a", t),
        sa.column("llm_id_b", t),
    )

    cases = {sa.text(f"'{k}'"): sa.text(f"'{v}'") for k, v in llm_ids_map.items()}
    op.execute(
        table.update().values(
            {
                "llm_id_a": sa.case(cases, value=table.c.llm_id_a),
                "llm_id_b": sa.case(cases, value=table.c.llm_id_b),
            }
        )
    )


# end custom


def upgrade() -> None:
    """Upgrade schema."""
    # start custom
    # First update comparison 'llm_id_a|b' with old id => corresponding uuid as string
    update_table_ids()
    # end custom

    # Then alter comparison 'llm_id_a|b' with auto convertion to uuid
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comparison",
        "llm_id_a",
        existing_type=sa.VARCHAR(),
        type_=sa.Uuid(),
        existing_nullable=False,
        postgresql_using='"llm_id_a"::uuid',  # custom
    )
    op.alter_column(
        "comparison",
        "llm_id_b",
        existing_type=sa.VARCHAR(),
        type_=sa.Uuid(),
        existing_nullable=False,
        postgresql_using='"llm_id_b"::uuid',  # custom
    )
    op.create_foreign_key(
        "comparison_llm_id_a_fkey", "comparison", "llm_data", ["llm_id_a"], ["id"]
    )  # custom key
    op.create_foreign_key(
        "comparison_llm_id_b_fkey", "comparison", "llm_data", ["llm_id_b"], ["id"]
    )  # custom key
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # First convert comparison 'llm_id_a|b' uuid to string

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "comparison_llm_id_b_fkey", "comparison", type_="foreignkey"
    )  # custom key
    op.drop_constraint(
        "comparison_llm_id_a_fkey", "comparison", type_="foreignkey"
    )  # custom key
    op.alter_column(
        "comparison",
        "llm_id_b",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using='"llm_id_b"::text',  # custom
    )
    op.alter_column(
        "comparison",
        "llm_id_a",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using='"llm_id_a"::text',  # custom
    )
    # ### end Alembic commands ###

    # start custom
    # Then update comparison 'llm_id_a|b' with stringified uuid => corresponding old id
    update_table_ids(reversed=True)
    # end custom
