"""link Comparison.llm_id_a|b to LLMData.id

Revision ID: c6d5610142dc
Revises: 4e31217520dd
Create Date: 2026-06-15 12:41:36.607686

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6d5610142dc"
down_revision: Union[str, Sequence[str], None] = "4e31217520dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comparison",
        "llm_id_a",
        existing_type=sa.VARCHAR(),
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    op.alter_column(
        "comparison",
        "llm_id_b",
        existing_type=sa.VARCHAR(),
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "comparison", "llm_data", ["llm_id_a"], ["id"])
    op.create_foreign_key(None, "comparison", "llm_data", ["llm_id_b"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comparison", type_="foreignkey")
    op.drop_constraint(None, "comparison", type_="foreignkey")
    op.alter_column(
        "comparison",
        "llm_id_b",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "comparison",
        "llm_id_a",
        existing_type=sa.Uuid(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
