"""add Comparison 'anonymous_user_hash'

Revision ID: f7f638e57c03
Revises: c523a8830386
Create Date: 2026-07-06 13:46:53.928592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7f638e57c03'
down_revision: Union[str, Sequence[str], None] = 'c523a8830386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparison', sa.Column('anonymous_user_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparison', 'anonymous_user_hash')
    # ### end Alembic commands ###
