services:
  frontend-da:
    build:
      context: ../../../frontend
      dockerfile: ../devops/docker/Dockerfile.front
    depends_on:
      - backend-da
    environment:
      PUBLIC_API_LOCAL_URL: "http://backend-da:80"
      PUBLIC_API_URL: "${PUBLIC_API_URL:-https://ai-arenaen.dk}"
    ports:
      - "3002:3000"

  backend-da:
    environment:
      LOGDIR: /data
      DEFAULT_COUNTRY_PORTAL: da
      COMPARIA_DB_URI: "${COMPARIA_DB_URI_DA:-postgresql://postgres:postgres@postgres-da:5432/comparia_da}"
      COMPARIA_REDIS_HOST: redis-da
      OPENROUTER_API_KEY:
      ORDBOGEN_API_KEY:
      GOOGLE_APPLICATION_CREDENTIALS:
      HF_PUSH_DATASET_KEY_DA:
      AWS_SECRET_ACCESS_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_ENDPOINT_URL:
      AWS_DEFAULT_REGION:
      SENTRY_DSN:
      SENTRY_ENVIRONMENT:
      SENTRY_SAMPLE_RATE:
      LOG_FORMAT:
      ALTCHA_HMAC_KEY:
    build:
      context: ../../..
      dockerfile: devops/docker/Dockerfile
    ports:
      - "8002:80"
