services:
  frontend-da:
    build:
      context: ../../../frontend
      dockerfile: ../devops/docker/Dockerfile.front
    depends_on:
      - backend-da
    environment:
      PUBLIC_API_LOCAL_URL: "http://backend-da:80"
      PUBLIC_API_URL: "${PUBLIC_API_URL:-https://ai-arenaen.dk}"
    ports:
      - "3002:3000"

  backend-da:
    env_file: .env.da
    environment:
      LOGDIR: /data
      COMPARIA_DB_URI: "${COMPARIA_DB_URI_DA:-postgresql://postgres:postgres@postgres-da:5432/comparia_da}"
      COMPARIA_REDIS_HOST: redis-da
    build:
      context: ../../..
      dockerfile: devops/docker/Dockerfile
    ports:
      - "8002:80"
    depends_on:
      - postgres-da
      - redis-da

  postgres-da:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comparia_da
    volumes:
      - db-data-da:/var/lib/postgresql/data
      - ../../db-init/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5434:5432"

  redis-da:
    image: redis
    ports:
      - "127.0.0.1:6381:6379"

volumes:
  db-data-da:
